- hosts: k8ss
  become: true
  vars_files:
    - group_vars/current.yaml


  tasks:
  
  
  - name: "Change repo for upgrade kubernetes"
    shell:  "{{item}}"      
    loop:
      - curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring-30.gpg
      - echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring-30.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /" | tee /etc/apt/sources.list.d/kubernetes.list



  - name: "Upgrade kubernetes to 30"
    shell:  "{{item}}"      
    loop:
      - apt-mark unhold kubeadm
      - apt-get update
      - apt-get install -y kubeadm="1.30.3-*"
      - apt-mark hold kubeadm
      - kubeadm upgrade node
      - kubectl drain --ignore-daemonsets $HOSTNAME 
      - apt-mark unhold kubelet kubectl
      - apt-get install -y kubelet="1.30.3-*" kubectl="1.30.3-*"
      - apt-mark hold kubelet kubectl
      - systemctl daemon-reload
      - systemctl restart kubelet
      - kubectl uncordon $HOSTNAME