

apiVersion: v1
kind: Pod
metadata:
  namespace: homework
  name: web
  labels:
    app.kubernetes.io/name: web  
spec:

  nodeSelector:
    kubernetes.io/hostname: k8s-w001
  initContainers:
    - name: init
      image: alpine:latest
      command: ['sh', '-c', "echo '<html><center><h1>Homework01</h1></center><html>' > /init/index.html"]
      volumeMounts:
        - name: homework
          mountPath: "/init"
  containers:
    - name: web
      image: nginx:latest
      volumeMounts:
        - name: homework
          mountPath: "/homework"
        - name: default
          mountPath: "/etc/nginx/conf.d/default.conf"
      lifecycle:
        preStop:
          exec:
            command: ["/bin/sh", "-c", "rm /homework/index.html"]
      
      ports:
        - containerPort: 8000
          name: http
      
      
          
  volumes:
        - name: homework
          emptyDir: {}
        - name: default
          hostPath:
            path: /root/otus/nginx/default.conf
            type: File
            
            
            
---

apiVersion: v1
kind: Service
metadata:
  namespace: homework
  name: web
  labels:
    app.kubernetes.io/name: web
spec:
  ports:
    - port: 8000
      targetPort: 8000      
  selector:
    app.kubernetes.io/name: web
  type: ClusterIP
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  