apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority: ca.crt
    server: https://192.168.15.106:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    namespace: homework
    user: cd
  name: cd-context
current-context: cd-context
users:
- name: cd
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImtNYkxWdXNqb1doV2NUdG9TU1QtdVVjN1dUOU5Zb3BScDJBNHNBdGt2cjAifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIuaGQubG9jYWwiXSwiZXhwIjoxNzU1MjczNDk0LCJpYXQiOjE3NTUxODcwOTQsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmhkLmxvY2FsIiwianRpIjoiNjEyODMwZTQtOTBmMS00ODVkLTk0YTYtMTM0YWU3ZGQwNjNlIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJob21ld29yayIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJjZCIsInVpZCI6ImQ0YzhjY2IyLTY3MjMtNDZmNi04N2I4LTk0NmE4ODM0NTViOSJ9fSwibmJmIjoxNzU1MTg3MDk0LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6aG9tZXdvcms6Y2QifQ.qddOVGwNW0Mw2c74KWO_6Z80J2jGQmKueKkCfxq6mpQJSNij8vmJrSO9sjpQu1o-06EbUxhtXX6wyviDdu9sbu9ZSpxotaujgcHJTdhQtR6feobuY73B68VbrkUNM6MqH5rCC1xsmQJPhcF51IOm-VqiyKPrYGyGBtaMl8u9Qxxm41nTLZfLJvT2kM9VVXyqgC4CkePbnNWIlUQerYWmI4Tlcx2j2hI4fdP9cW_EjHE4IW09EfoupyQuopUdbWY9K4IfR43JVnDC4uDhulgk9nUjpbkM_jQvqf70Q-szZBWpokQWI-jfRuRSvKltds8d4cHlqRpJU0k_nFm0r2tYMA
