---
apiVersion: otus.homework/v1
kind: MySQL
metadata:
  name: mysql-test
  namespace: default
  finalizers: []
spec:
  image: rybnovn/mysql:1.0
  database: testdb
  password: secret
  storage_size: "1"
