
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role-manager
rules:
- apiGroups: ["otus.homework"]
  resources: ["mysqls"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["services","persistentvolumes","persistentvolumeclaims","events"]
  verbs: ["*"]
- apiGroups: ["apps","extensions"]
  resources: ["deployments","deployments/status"]
  verbs: ["*"]
- apiGroups: ["events.k8s.io"]
  resources: ["events"]
  verbs: ["*"]
    
    
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-manager-binding
subjects:
  - kind: ServiceAccount
    name: manager-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: role-manager
  apiGroup: rbac.authorization.k8s.io