apiVersion: v1
kind: ConfigMap
metadata:
  name: web-nginx-configmap
  namespace: homework
data:
  default.conf: |-
    server {
    listen       8000;
    listen  [::]:8000;
    server_name  localhost;
    

    location / {
        root   /homework;
        index  index.html index.htm;
    
    }

    location /homepage {
        root   /homework;
        try_files $uri $uri/ /index.html;


    }

   


    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }



    }
---


  

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: homework
  name: test-web-configmap
data:
  file: |-
    key1: "1"  
    key2: "2"
    key3: "3"
    .
